debug the device not exist on host case

diff --git a/theanompi/bin/tmlauncher b/theanompi/bin/tmlauncher
--- a/theanompi/bin/tmlauncher
+++ b/theanompi/bin/tmlauncher
@@ -14,6 +14,8 @@
 RED='\e[1;31m'
 NC='\e[0m' # No Color or other format
 
+set -e
+
 python -c "import theanompi"
 if [[ $? ]]
 then
@@ -21,7 +23,7 @@ then
 	theanompipath=$(python -c "import theanompi;print theanompi.__path__[0]")
 	echo $theanompipath
 else
-	echo -e "${RED}Error${NC}: Theano-MPI not found"
+	echo -e "$LINENO: ${RED}Error${NC}: Theano-MPI not found" >&2
 	exit 1
 fi
 
@@ -55,7 +57,7 @@ case $i in
 	;;
     *)
         # unknown option
-		echo -e "${RED}Error${NC}: unknown option ${i}"
+		echo -e "$LINENO: ${RED}Error${NC}: unknown option ${i}" >&2
 		exit 1
     ;;
 esac
@@ -68,7 +70,7 @@ RULE=${RULE}
 
 if [[ (-z $CONFIG) && (-z $MODELFILE) && (-z $MODELCLASS) && (-z $RULE) ]]
 then
-	echo -e "${RED}Error${NC}: Neither config nor run options provided"
+	echo -e "$LINENO: ${RED}Error${NC}: Neither config nor run options provided" >&2
 	exit 1
 elif [[ ! -z $CONFIG ]]
 then
@@ -82,17 +84,17 @@ then
 fi
 
 if [[ -z $MODELFILE ]]; then
-	echo -e "${RED}Error${NC}: NO modelfile provided"
+	echo -e "$LINENO: ${RED}Error${NC}: NO modelfile provided" >&2
 	exit 1
 fi
 
 if [[ -z $MODELCLASS ]]; then
-	echo -e "${RED}Error${NC}: NO modelclass provided"
+	echo -e "$LINENO: ${RED}Error${NC}: NO modelclass provided" >&2
 	exit 1
 fi
 
 if [[ -z $RULE ]]; then
-	echo -e "${RED}Error${NC}: NO rule provided"
+	echo -e "$LINENO: ${RED}Error${NC}: NO rule provided" >&2
 	exit 1
 fi
 
@@ -136,6 +138,9 @@ function find_cpuset_in_topo_by_GPUnumber
 {
 	declare -a _lines=("${!1}") # pass in array variable
 	_GPUnumber=$2 
+	local cpuset=""
+	local number=""
+	
 	for d in "${_lines[@]}"
 	do
 		# ^ = start of line, $ = end of liine, \s = space, 
@@ -161,8 +166,8 @@ function check_device_name
 	name=$1
 	if [[ ! $name =~ cuda[0-9]+ ]]
 	then
-		echo -e "${RED}Error${NC}: device name $d is not in the format of cuda[0-9]+"
-	exit 1
+		echo -e "$LINENO: ${RED}Error${NC}: device name $d is not in the format of cuda[0-9]+" >&2
+		exit 1
 	fi
 }
 
@@ -170,9 +175,9 @@ function check_device_name
 # separate a colon connected 'host:dev0,dev1,...' string into an ('host:dev0', 'host:dev1', ...) array
 function separate_host_dev_string
 {
-	string=$1
-	host="${string%%:*}"
-	devlist="${string##*:}"
+	local string=$1
+	local host="${string%%:*}"
+	local devlist="${string##*:}"
 	set -f
 	_dev=(${devlist//,/ }) # a comma delimited string of device names
 	
@@ -198,35 +203,45 @@ function separate_host_dev_string
 function get_cpusetarray_on_host
 {
 	declare -a arr=("${!1}") # pass in array variable
-	host=$2
-	BIND=$3
+	local host=$2
+	local BIND=$3
 
 	mapfile -t lines < <(ssh $host nvidia-smi topo -m | grep "^GPU[0-9]\+")
 	_SIZE=${#lines[@]} # shows the amount of available GPUs
 	
-	sz=${#arr[@]}
+	local sz=${#arr[@]}
 	
 	if [[ $sz -gt $_SIZE ]]
 	then
-		echo -e "${RED}Error${NC}: there are not as many GPUs as requested on host $host ($sz requested, $_SIZE exist(s))"
+		echo -e "$LINENO: ${RED}Error${NC}: there are not as many GPUs as requested on host $host ($sz requested, $_SIZE exist(s))" >&2
 		exit 1
 	fi
 	
-	if [[ ! -z $BIND ]]
+	local cpuset=()
+	local cpu=""
+	local GPUnumber=""
+	
+	for d in "${arr[@]}"
+	do
+		if [[ ! $d =~ $host:cuda[0-9]+ ]]
+		then
+	    	echo -e "$LINENO: ${RED}Error${NC}: device name $d is not in the format of $host:cuda[0-9]+" >&2
+	    	exit 1
+		else
+			GPUnumber=${d#*:cuda}
+			cpu=$(find_cpuset_in_topo_by_GPUnumber lines[@] $GPUnumber)
+			if [[ -z $cpu ]]
+			then
+				echo -e "$LINENO: ${RED}Error${NC}: device ${d#*:} does not exist on host $host" >&2
+				exit 1
+			fi
+			cpuset+=($(range_expand $cpu))
+		fi
+	done
+		
+	if [[ -z $BIND ]]
 	then
 		cpuset=()
-		for d in "${arr[@]}"
-		do
-			if [[ ! $d =~ $host:cuda[0-9]+ ]]
-			then
-		    	echo -e "${RED}Error${NC}: device name $d is not in the format of $host:cuda[0-9]+"
-		    	exit 1
-			else
-				GPUnumber=${d#*:cuda}
-				cpu=$(find_cpuset_in_topo_by_GPUnumber lines[@] $GPUnumber)
-				cpuset+=($(range_expand $cpu))
-			fi
-		done
 	fi
 	
 	echo ${cpuset[@]}
@@ -243,12 +258,12 @@ function get_cpusetarray_on_host
 #			(global) SIZE : the total number of devices being used on all hosts
 function get_cpu_dev_array
 {
-	BIND=$1
-	num_host=${#DEVICES[@]}	
+	local BIND=$1
+	local num_host=${#DEVICES[@]}	
 
 	if [[ num_host -eq 0 ]] || [[ -z $DEVICES ]]
 	then
-		echo -e "${RED}Error${NC}: DEVICES empty"
+		echo -e "$LINENO: ${RED}Error${NC}: DEVICES empty" >&2
 		exit 1
 	elif [[ num_host -eq 1 ]] && [[ ! $DEVICES =~ ^.*:.*$ ]]
 	then
@@ -286,7 +301,7 @@ get_cpu_dev_array $BIND
 #			(global) env
 function get_env
 {
-	BIND=$1
+	local BIND=$1
 	
 	env="--mca mpi_max_info_val 10240 --mca mpi_warn_on_fork 0 --mca btl_smcuda_use_cuda_ipc 1 --mca mpi_common_cuda_cumemcpy_async 1 -x PATH=$PATH -x LIBRARY_PATH=$LIBRARY_PATH -x LD_LIBRARY_PATH=$LD_LIBRARY_PATH -x CPATH=$CPATH"
 	if [[ -z $BIND ]]
@@ -314,21 +329,21 @@ get_env $BIND
 #			(global): cpusetarray
 function BSP
 {
-	BSP_sync_type=$BSP_SYNC_TYPE
+	local BSP_sync_type=$BSP_SYNC_TYPE
 	if [[ -z $BSP_sync_type ]]
 	then
 	BSP_sync_type='cdd'
 	fi
 	
-	BSP_exch_strategy=$BSP_EXCH_STRATEGY
+	local BSP_exch_strategy=$BSP_EXCH_STRATEGY
 	if [[ -z $BSP_exch_strategy ]]
 	then
 	BSP_exch_strategy='nccl32'
 	fi
 	
-	args="$BSP_sync_type $BSP_exch_strategy $MODELFILE $MODELCLASS"
+	local args="$BSP_sync_type $BSP_exch_strategy $MODELFILE $MODELCLASS"
 
-	command_array=()
+	local command_array=()
 	command_array+=('mpirun')
 
 	for (( index=0; index<$SIZE; index++ ))
@@ -361,9 +376,9 @@ function BSP
 function EASGD
 {
 	
-	args="$MODELFILE $MODELCLASS"
+	local args="$MODELFILE $MODELCLASS"
 	
-	command_array=()
+	local command_array=()
 	command_array+=('mpirun')
 	
 	for (( index=0; index<$SIZE; index++ ))
@@ -399,9 +414,9 @@ function EASGD
 function GOSGD
 {
 	
-	args="$MODELFILE $MODELCLASS"
+	local args="$MODELFILE $MODELCLASS"
 
-	command_array=()
+	local command_array=()
 	command_array+=('mpirun')
 
 	for (( index=0; index<$SIZE; index++ ))
@@ -436,7 +451,7 @@ case $RULE in
     ;;
     *)
         # unknown option
-		echo -e "${RED}Error${NC}: unknown rule ${RULE}"
+		echo -e "$LINENO: ${RED}Error${NC}: unknown rule ${RULE}" >&2
 		exit 1
     ;;
 esac
