debug the cpusetarray-devarray unmatching case

diff --git a/theanompi/bin/tmlauncher b/theanompi/bin/tmlauncher
--- a/theanompi/bin/tmlauncher
+++ b/theanompi/bin/tmlauncher
@@ -12,7 +12,7 @@
 ##################
 
 RED='\e[1;31m'
-NC='\e[0m' # No Color
+NC='\e[0m' # No Color or other format
 
 python -c "import theanompi"
 if [[ $? ]]
@@ -79,7 +79,6 @@ then
 	echo "RULE = $RULE"
 	echo "MODELFILE = $MODELFILE"
 	echo "MODELCLASS = $MODELCLASS"
-	echo "SIZE = $SIZE"
 fi
 
 if [[ -z $MODELFILE ]]; then
@@ -104,6 +103,11 @@ fi
 # Getting cpu-affinity array corresponding to device array
 ##############################
 ##############################
+
+# expand ranges complex like '1-3,4-6' to '1,2,3,4,5,6'
+# @param: 
+#			$1: a string of range complex
+# output: a string of comma-separated values
 function range_expand
 {
     IFS=,
@@ -122,7 +126,43 @@ function range_expand
     # to return a comma-separated value: 
 }
 
-function get_cpu_dev_list
+# though the output lines of nvidia-smi topo -m 
+# find the cpu affinity ranges corresponding to a specific GPU number 
+# @param: 
+#			$1: output lines of nvidia-smi topo -m
+#			$2: a GPU number 
+# output: a string of cpu affinity ranges
+function find_cpuset_in_topo_by_GPUnumber
+{
+	declare -a _lines=("${!1}") # pass in array variable
+	_GPUnumber=$2 
+	for d in "${_lines[@]}"
+	do
+		# ^ = start of line, $ = end of liine, \s = space, 
+		# \[\] = a set of characters to be matched
+		# \+ = match one or more, \(\) = store the match inside bracket into variable 1
+	    
+		number=$(echo $d | sed -n -e 's/^\(GPU[0-9]\+\).*/\1/p')
+		number=${number#GPU}
+		if [[ $number == $_GPUnumber ]]
+		then
+			cpuset=$(echo $d | sed -n -e 's/^.*\s\+\([0-9,-]\+\)$/\1/p')
+			break
+		fi
+	done
+	
+	echo $cpuset
+}
+
+# get the devarray by parsing DEVICES
+# get the corresponding cpusetarray by parsing nvidia-smi topo -m
+# @param: 
+#			$1: a flag to control whether do core binding or not
+# output: 
+#			(global) devarray
+#			(global) cpusetarray
+#			(global) SIZE
+function get_cpu_dev_array
 {
 	BIND=$1
 	# generate a devarray according to DEVICES or SIZE
@@ -140,6 +180,14 @@ function get_cpu_dev_list
 			echo -e "${RED}Error${NC}: the length of device list (${#devarray[@]}) does not match the specified size (${SIZE})"
 			exit 1
 		else
+			for d in "${devarray[@]}"
+			do
+			  if [[ ! $d =~ cuda[0-9]+ ]]
+			  then
+			    echo -e "${RED}Error${NC}: device name $d is not in the format of cuda[0-9]+"
+			    exit 1
+			  fi
+			done
 			SIZE=${#devarray[@]}
 		fi		
 	elif [[ ! -z $SIZE && -z $DEVICES ]]
@@ -151,54 +199,70 @@ function get_cpu_dev_list
 		done
 	fi
 	
-	cpulist=($(nvidia-smi topo -m | sed -n -e 's/^.*\s\+\([0-9,-]\+\)$/\1/p'))
 	
+	mapfile -t lines < <(nvidia-smi topo -m | grep "^GPU[0-9]\+")
+	_SIZE=${#lines[@]} # shows the amount of available GPUs
 	
-	
-	_SIZE=${#cpulist[@]}
 	if [[ $SIZE -gt $_SIZE ]]
 	then
 		echo -e "${RED}Error${NC}: there are not as many GPUs as requested ($SIZE requested, $_SIZE exist(s))"
-		exit
+		exit 1
 	fi	
-	
-	#TODO reorder cpulist by device name to match the order in DEVICES during constructing cpulist_expand
-	
-	cpulist_expand=()
 	
 	if [[ ! -z $BIND ]]
 	then
-	
-		for index in ${!cpulist[*]}
+		cpusetarray=()
+		for d in "${devarray[@]}"
 		do
-			tobeexpand=${cpulist[$index]}
-			cpulist_expand+=($(range_expand $tobeexpand))
+			if [[ ! $d =~ cuda[0-9]+ ]]
+			then
+		    	echo -e "${RED}Error${NC}: device name $d is not in the format of cuda[0-9]+"
+		    	exit 1
+			else
+				GPUnumber=${d#cuda}
+				cpuset=$(find_cpuset_in_topo_by_GPUnumber lines[@] $GPUnumber)
+				cpusetarray+=($(range_expand $cpuset))
+			fi
 		done
 	fi
 }
 
-get_cpu_dev_list $BIND
+get_cpu_dev_array $BIND
 
+# get the env options used in calling mpirunm
+# @param: 
+#			$1: a flag to control whether do core binding or not
+# output: 
+#			(global) env
 function get_env
 {
 	BIND=$1
 	
 	if [[ -z $BIND ]]
 	then
-		env="--mca mpi_warn_on_fork 0 --mca btl_smcuda_use_cuda_ipc 1 --mca mpi_common_cuda_cumemcpy_async 1 --bind-to none"
+		env="--mca mpi_max_info_val 10240 --mca mpi_warn_on_fork 0 --mca btl_smcuda_use_cuda_ipc 1 --mca mpi_common_cuda_cumemcpy_async 1 --bind-to none"
 	else
-		env="--mca mpi_warn_on_fork 0 --mca btl_smcuda_use_cuda_ipc 1 --mca mpi_common_cuda_cumemcpy_async 1"
+		env="--mca mpi_max_info_val 10240 --mca mpi_warn_on_fork 0 --mca btl_smcuda_use_cuda_ipc 1 --mca mpi_common_cuda_cumemcpy_async 1"
 	fi
 }
 
 
 get_env $BIND
+
 ##################
 ##################
 # launching a rule
 ##################
 ##################
 
+
+# launch Bulk Synchronous Parallel training
+# @param: 
+#			(global): SIZE, MODELFILE, MODELCLASS
+#			(global): BSP_SYNC_TYPE, BSP_EXCH_STRATEGY
+#			(global): env
+#			(global): devarray
+#			(global): cpusetarray
 function BSP
 {
 	BSP_sync_type=$BSP_SYNC_TYPE
@@ -215,14 +279,12 @@ function BSP
 	
 	args="$BSP_sync_type $BSP_exch_strategy $MODELFILE $MODELCLASS"
 
-	
-
 	command_array=()
 	command_array+=('mpirun')
 
 	for (( index=0; index<$SIZE; index++ ))
 	do 
-		command_array+=("$env -n 1 python -u $theanompipath/worker.py ${devarray[$index]} $args ${cpulist_expand[$index]}")
+		command_array+=("$env -n 1 python -u $theanompipath/worker.py ${devarray[$index]} $args ${cpusetarray[$index]}")
 		if [[ $index -ne $((SIZE-1)) ]]
 		then
 			command_array+=(":")
@@ -231,23 +293,28 @@ function BSP
 
 	echo
 	echo "Theano-MPI started $SIZE BSP($BSP_sync_type,$BSP_exch_strategy) workers"
-	echo "by executing: ${command_array[@]/#/}"
+	#echo "by executing: ${command_array[@]/#/}"
 	
 	${command_array[@]/#/}
 	
 }
 
+
+# launch Elastic Averaging SGD training
+# @param: 
+#			(global): SIZE, MODELFILE, MODELCLASS
+#			(global): env
+#			(global): devarray
+#			(global): cpusetarray
 function EASGD
 {
 	
 	args="$MODELFILE $MODELCLASS"
-
-
 	
 	command_array=()
 	command_array+=('mpirun')
 	
-	for index in ${!cpulist_expand[*]}
+	for (( index=0; index<$SIZE; index++ ))
 	do 
 		if [[ $index -eq 0 ]] 
 		then
@@ -256,7 +323,7 @@ function EASGD
 		else
 			file='easgd_worker.py'
 		fi
-		command_array+=("$env -n 1 python -u $theanompipath/$file ${devarray[$index]} $args ${cpulist_expand[$index]}")
+		command_array+=("$env -n 1 python -u $theanompipath/$file ${devarray[$index]} $args ${cpusetarray[$index]}")
 		if [[ $index -ne $((SIZE-1)) ]]
 		then
 			command_array+=(":")
@@ -265,24 +332,29 @@ function EASGD
 	
 	echo
 	echo "Theano-MPI started one EASGD server and ${SIZE-1} EASGD workers"
-	echo "by executing: ${command_array[@]/#/}"
+	#echo "by executing: ${command_array[@]/#/}"
 	
 	${command_array[@]/#/}
 	
 }
 
+# launch Gossip SGD training
+# @param: 
+#			(global): SIZE, MODELFILE, MODELCLASS
+#			(global): env
+#			(global): devarray
+#			(global): cpusetarray
 function GOSGD
 {
 	
 	args="$MODELFILE $MODELCLASS"
 
-
 	command_array=()
 	command_array+=('mpirun')
 
-	for index in ${!cpulist_expand[*]}
+	for (( index=0; index<$SIZE; index++ ))
 	do 
-		command_array+=("$env -n 1 python -u $theanompipath/gosgd_worker.py ${devarray[$index]} $args ${cpulist_expand[$index]}")
+		command_array+=("$env -n 1 python -u $theanompipath/gosgd_worker.py ${devarray[$index]} $args ${cpusetarray[$index]}")
 		if [[ $index -ne $((SIZE-1)) ]]
 		then
 			command_array+=(":")
@@ -291,7 +363,7 @@ function GOSGD
 
 	echo
 	echo "Theano-MPI started $SIZE GOSGD workers"
-	echo "by executing: ${command_array[@]/#/}"
+	#echo "by executing: ${command_array[@]/#/}"
 	
 	${command_array[@]/#/}
 	
